name: Tests

on:
  push:
    branches: 
       - "*"
  pull_request:
    branches:
       - "*"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # or, you can use 1.22
        channel: 'stable'
        cache: true
    - run: flutter test --coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
