name: Android Build

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: "17"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: 'stable'
          cache: true

      - name: Create key.properties
        run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ./android/key.properties
          echo storePassword=\${{ secrets.KEY_STORE_PASSWORD }} >> ./android/key.properties
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ./android/key.properties

      - name: Load key
        run: echo "${{ secrets.KEYSTORE_JKS_RELEASE }}" | base64 --decode > android/app/release-key.jks

      - name: Turn off analytics
        run: flutter config --no-analytics

      - name: Pub Get Packages
        run: flutter pub get

    
      - name: Build APK
        run: flutter build apk --release --split-per-abi --flavor dev

      - name: Save APKs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 3
